version: "3"

services:
  app-backend:
    build:
      context: ./pp-sms-api
      dockerfile: Dockerfile
    container_name: from_russia
    ports:
      - "9090:8080"
    networks:
      - db-network
    links:
       - db
    restart: always
    depends_on: 
      - db

  db:
    image: mysql
    container_name: with_love
    networks:
      - db-network
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always

networks:
  db-network:
